edition = "2024"
style_edition = "2024"
unstable_features = true

use_small_heuristics = "Max"
comment_width = 76
doc_comment_code_block_width = 76
attr_fn_like_width = 76
max_width = 100

binop_separator = "Back"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true
