[build]
rustflags = ["--cfg", "tracing_unstable"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "--cfg", "tracing_unstable",
    "--remap-path-prefix=/app=.",
    "-C", "codegen-units=1",
    "-C", "embed-bitcode=no",
    "-C", "link-arg=-static-libgcc",
    "-C", "link-arg=-Wl,--build-id=none",
    "-C", "metadata=target",
    "-C", "target-feature=+crt-static",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "--cfg", "tracing_unstable",
    "--remap-path-prefix=/app=.",
    "-C", "codegen-units=1",
    "-C", "embed-bitcode=no",
    "-C", "link-arg=-static-libgcc",
    "-C", "link-arg=-Wl,--build-id=none",
    "-C", "metadata=target",
    "-C", "target-feature=+crt-static",
]
